[package]
name = "kernel-proto"
version.workspace = true
edition.workspace = true

[dependencies]
prost.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
thiserror.workspace = true
anyhow.workspace = true
kernel-core = { workspace = true }
kernel-sdk = { workspace = true }

[build-dependencies]
prost-build = "0.13"
