#!/bin/bash
# Simple task watcher: poll hh-kernel/tasks for .finished.md files
# For each found, run appropriate integration test (if present).
# If test passes -> create a .verified.md file; if fails -> create a follow-up task file.

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TASK_DIR="$ROOT_DIR/tasks"
TEST_DIR="$ROOT_DIR/tests"
PROCESSED_DIR="$TASK_DIR/processed"
mkdir -p "$PROCESSED_DIR"

log() { echo "[task-watcher] $(date --iso-8601=seconds) $*"; }

while true; do
  shopt -s nullglob
  for f in "$TASK_DIR"/*.finished.md; do
    base=$(basename "$f" .finished.md)
    # Skip if already processed marker exists
    if [ -e "$PROCESSED_DIR/$base.finished.processed" ]; then
      continue
    fi

    log "Found finished marker: $f (task: $base)"

    case "$base" in
      001-record-keyframes)
        testfile="$TEST_DIR/check_record_keyframes.js"
        if [ -f "$testfile" ]; then
          log "Running test for $base: $testfile"
          outfile="/tmp/${base}_test.out"
          set +e
          node "$testfile" > "$outfile" 2>&1
          rc=$?
          set -e
          if [ $rc -eq 0 ]; then
            log "Test passed for $base"
            # create verified file
            cat > "$TASK_DIR/${base}.verified.md" <<EOF
任务: ${base}
状态: VERIFIED
时间: $(date --iso-8601=seconds)
说明: 集成测试通过。
EOF
            git -C "$ROOT_DIR" add "$TASK_DIR/${base}.verified.md"
            git -C "$ROOT_DIR" commit -m "test(hh-kernel): ${base} verified by integration tests\n\nAuto-generated by task_watcher" || true
          else
            log "Test FAILED for $base, creating follow-up task"
            # Create follow-up task detailing failure
            cat > "$TASK_DIR/${base}-fix.md" <<EOF
标题: ${base} - 集成测试失败，需要 kernel 端进一步修复

背景: 自动化集成测试在执行后失败。请查看下面的测试输出并修复内核实现以满足任务要求。

测试输出:

">
$(sed -n '1,200p' "$outfile")


EOF
            git -C "$ROOT_DIR" add "$TASK_DIR/${base}-fix.md"
            git -C "$ROOT_DIR" commit -m "chore(hh-kernel): ${base} failed integration test, created follow-up task" || true
          fi
          # mark processed
          touch "$PROCESSED_DIR/$base.finished.processed"
        else
          log "No testfile for $base (expected: $testfile). Creating follow-up task to add test."
          cat > "$TASK_DIR/${base}-add-test.md" <<EOF
标题: 为 ${base} 增加集成测试

背景: ${base} 标记已完成，但仓库中未找到对应的集成测试 (hh-kernel/tests/...).
请实现一个可以验证该任务的集成测试，并将其放在 hh-kernel/tests/ 下，命名规范 check_${base}.js。

验收标准:
- 能够在 CI/本地运行： node hh-kernel/tests/check_${base}.js
- 测试在成功时退出码 0，并在失败时返回非 0

EOF
          git -C "$ROOT_DIR" add "$TASK_DIR/${base}-add-test.md"
          git -C "$ROOT_DIR" commit -m "chore(hh-kernel): add task to create integration test for ${base}" || true
          touch "$PROCESSED_DIR/$base.finished.processed"
        fi
        ;;
      002-merge-keyframes)
        # If there is a dedicated test, run it; otherwise create follow-up to add test
        testfile="$TEST_DIR/check_merge_keyframes.js"
        if [ -f "$testfile" ]; then
          log "Running merge-keyframes test"
          outfile="/tmp/${base}_test.out"
          set +e
          node "$testfile" > "$outfile" 2>&1
          rc=$?
          set -e
          if [ $rc -eq 0 ]; then
            log "Merge keyframes test passed"
            cat > "$TASK_DIR/${base}.verified.md" <<EOF
任务: ${base}
状态: VERIFIED
时间: $(date --iso-8601=seconds)
说明: 集成测试通过。
EOF
            git -C "$ROOT_DIR" add "$TASK_DIR/${base}.verified.md" && git -C "$ROOT_DIR" commit -m "test(hh-kernel): ${base} verified by integration tests" || true
          else
            log "Merge keyframes test FAILED, creating follow-up"
            cat > "$TASK_DIR/${base}-fix.md" <<EOF
标题: ${base} - Merge KeyFrames 功能未通过集成测试

请查看测试输出并修复内核实现。

测试输出:

">
$(sed -n '1,200p' "$outfile")


EOF
            git -C "$ROOT_DIR" add "$TASK_DIR/${base}-fix.md" && git -C "$ROOT_DIR" commit -m "chore(hh-kernel): ${base} failed integration test, created follow-up task" || true
          fi
          touch "$PROCESSED_DIR/$base.finished.processed"
        else
          log "No merge keyframes test - creating task to add test"
          cat > "$TASK_DIR/${base}-add-test.md" <<EOF
标题: 为 ${base} 增加集成测试

请实现一个集成测试来验证 MergeKeyFrames 命令行为。

EOF
          git -C "$ROOT_DIR" add "$TASK_DIR/${base}-add-test.md" && git -C "$ROOT_DIR" commit -m "chore(hh-kernel): add task to create integration test for ${base}" || true
          touch "$PROCESSED_DIR/$base.finished.processed"
        fi
        ;;
      *)
        log "Unknown finished task: $base - creating generic follow-up"
        cat > "$TASK_DIR/${base}-review.md" <<EOF
标题: Review ${base}

说明: 发现 ${base}.finished.md，请 kernel 团队确认并提供对应的集成测试或说明。

EOF
        git -C "$ROOT_DIR" add "$TASK_DIR/${base}-review.md" && git -C "$ROOT_DIR" commit -m "chore(hh-kernel): review finished task ${base}" || true
        touch "$PROCESSED_DIR/$base.finished.processed"
        ;;
    esac
  done
  sleep 5
done
